# Base image
FROM node:21-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY . .

# Install app dependencies
RUN npm install

# Expose port
EXPOSE 3000

# Start the app in development mode
CMD ["npm", "run", "start:dev"]