version: '3.8'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: yourpassword
      DB_DATABASE: creativethinking
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: creativethinking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: yourpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
